[package]
name = "advent_of_code"
version = "0.0.1"
authors = ["Marc Jovani"]
edition = "2021"
default-run = "advent_of_code"

[lib]
doctest = false

[features]
test_lib = []

[dependencies]
petgraph = "0.6.4"
pico-args = "0.5.0"
z3 = {version="0.12.1"}
